# Add application configuration variables here.

development:
  STRIPE_PUBLISHABLE_KEY: pk_test_cpJAcb9Rx9PNrPw6ivG5P4cx
  STRIPE_SECRET_KEY: sk_test_8mNod3rk2WQ0ekQyB54gtJhE
  STRIPE_SIGNING_SECRET: whsec_zW9L7JMerM5l01pHfheSuTX2vwhNjTNG

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_cpJAcb9Rx9PNrPw6ivG5P4cx
  STRIPE_SECRET_KEY: sk_test_8mNod3rk2WQ0ekQyB54gtJhE
  STRIPE_SIGNING_SECRET: whsec_zW9L7JMerM5l01pHfheSuTX2vwhNjTNG

production:
  STRIPE_PUBLISHABLE_KEY: pk_test_cpJAcb9Rx9PNrPw6ivG5P4cx
  STRIPE_SECRET_KEY: sk_test_8mNod3rk2WQ0ekQyB54gtJhE
  STRIPE_SIGNING_SECRET: whsec_zW9L7JMerM5l01pHfheSuTX2vwhNjTNG