# Regardless which environment you are on, make sure that you use Postgres as your database on your development 
# environment, because 1) Postgres is currently the best open-source SQL databases on the market and 
# 2) we are going to deploy to Heroku, which uses Postgres as the database. It's always a good idea to keep
# your local development database the same as your database on production.
development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: ubuntu
  password:
  
  